from setuptools import setup, find_packages

setup(
    name="atomic-rose-tools-backend",
    version="1.0.0",
    description="Backend API for Atomic Rose Tools Store",
    author="NivoDev",
    author_email="nivo@example.com",
    packages=find_packages(),
    python_requires=">=3.9",
    install_requires=[
        "fastapi==0.104.1",
        "uvicorn[standard]==0.24.0",
        "motor==3.3.2",
        "pymongo==4.6.0",
        "beanie==1.23.6",
        "python-jose[cryptography]==3.3.0",
        "passlib[bcrypt]==1.7.4",
        "python-multipart==0.0.6",
        "argon2-cffi==23.1.0",
        "boto3==1.34.0",
        "botocore==1.34.0",
        "python-dotenv==1.0.0",
        "pydantic==2.5.0",
        "pydantic-settings==2.1.0",
        "httpx==0.25.2",
        "structlog==23.2.0",
        "fastapi-cors==0.0.6",
        "slowapi==0.1.9",
        "redis==5.0.1",
        "fastapi-mail==1.4.1",
    ],
)
