[build]
  # Build from the CRA backup folder
  base = "frontend-csr-backup"
  command = "npm ci && npm run build"
  # CRA outputs to /build (relative to base)
  publish = "build"

[build.environment]
  NODE_VERSION = "18.20.4"           # CRA 5 works great on Node 18
  NPM_VERSION = "10"
  NODE_ENV = "production"
  REACT_APP_API_BASE_URL = "https://store-6ryk.onrender.com/api/v1"
  GENERATE_SOURCEMAP = "false"
  # Helps older deps on Node 18 and avoids ESLint CI fails
  NODE_OPTIONS = "--openssl-legacy-provider"
  DISABLE_ESLINT_PLUGIN = "true"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# CSP Header
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.gstatic.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.gstatic.com;
      img-src 'self' data: https: blob:;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https:;
      media-src 'self' https: blob:;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
    '''

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# API proxy to backend
[[redirects]]
  from = "/api/*"
  to = "https://store-6ryk.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Health check proxy
[[redirects]]
  from = "/health"
  to = "https://store-6ryk.onrender.com/health"
  status = 200
  force = true

# SPA routing (catch-all for CRA routes)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
